on:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.APPARITOR_GITHUB_TOKEN }}

      - name: Setup go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417
        with:
          go-version-file: .tool-versions

      - name: Generate
        run: make generate

      - name: Commit
        uses: devops-infra/action-commit-push@f01d24007c469639f252dc88109ef96bfbff33db
        with:
          github_token: ${{ secrets.APPARITOR_GITHUB_TOKEN }}
          commit_message: "update"
