on:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.APPARITOR_GITHUB_TOKEN }}

      - name: Setup go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e
        with:
          go-version-file: .tool-versions

      - name: Generate
        run: make generate

      - name: Commit
        uses: devops-infra/action-commit-push@f066ea8e19660de57d3d3a4a0b9d294ea2612e20
        with:
          github_token: ${{ secrets.APPARITOR_GITHUB_TOKEN }}
          commit_message: "update"
