on:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.APPARITOR_GITHUB_TOKEN }}

      - name: Setup go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16
        with:
          go-version-file: .tool-versions

      - name: Generate
        run: make generate

      - name: Commit
        uses: devops-infra/action-commit-push@f066ea8e19660de57d3d3a4a0b9d294ea2612e20
        with:
          github_token: ${{ secrets.APPARITOR_GITHUB_TOKEN }}
          commit_message: "update"
